In [1]:
import numpy as np

In [2]:
np_array_1=np.array([1,2,3,4])
print(np_array_1)
print(type(np_array_1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
np_array_2=np.array([[1,2,3],[5,6,7]])
print(np_array_2)

[[1 2 3]
 [5 6 7]]


In [4]:
#array의 행의 수를 출력
print(np_array_2.ndim)
#array의 크기를 출력
print(np_array_2.shape)

2
(2, 3)


In [5]:
#0행렬 -> zeros(크기)
zero_array=np.zeros((3,4))
zero_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
#1로 채워질 행렬 -> ones(크기)
one_array=np.ones((3,4))
one_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
#full(크기, 채워줄 숫자)-> 0,1이 아닌 원하는 숫자로 채워서 행렬을 만들때 사용
full_array=np.full((2,2), 2)
full_array

array([[2, 2],
       [2, 2]])

In [8]:
#단위행렬 만드는 함수-> eye(크기)
eye_array=np.eye(3)
eye_array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
#임의의 값을 가지는 행렬-> random.random(크기)
random_array=np.random.random((4,2))
random_array

array([[0.94862672, 0.33515243],
       [0.8500846 , 0.30957029],
       [0.06995692, 0.42000188],
       [0.64572399, 0.37986395]])

In [10]:
#arange()-> 순차적인 데이터를 만들때 사용
arange_array=np.arange(10)
arange_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
#
arange_array_2=np.arange(2,10,2)
arange_array_2

array([2, 4, 6, 8])

In [12]:
#행렬의 구조를 변경하는 함수-> reshape(크기)
reshape_array=arange_array.reshape((2,5))
reshape_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
reshape_array=arange_array.reshape((3,3)) #데이터 크기와 모양의 크기가 맞지 않음
reshape_array

ValueError: cannot reshape array of size 10 into shape (3,3)

In [ ]:
#행렬 연산
x=np.array([1,2,3])
y=np.array([4,5,6])

In [ ]:
#행렬의 덧셈-> x+y / np.add(x,y)
#행렬의 뺄셈-> x-y / np.substract(x,y)
#행렬의 곱셈-> x*y / np.multiply(x,y)
#행렬의 나눗셈-> x/y / np.divide(x,y)
print(x+y)


[5 7 9]


In [ ]:
#행렬의 행렬곱 -> x@y / np.dot(x,y)
x2=np.array([[1,2],[3,4]])
y2=np.array([[5,6],[7,8]])

print(x2@y2)
print(np.dot(x2,y2))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
